# Site Settings
locale                   : "en-US"
title                    : "Aditya Sundar"
title_separator          : "-"
name                     : &name "Aditya Sundar"
description              : &description "personal description"
url                      : https://adisun94.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "adisun94/adisun94.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml

# Google analytics ID: Remove or use your own!
google_analytics: UA-167467135-1
google_analytics_4: G-02KDGRRB2T
google_tag_manager: GTM-TZ9Z7HZ

# Site Author
author:
  name             : "Aditya Sundar"
  avatar           : "Aditya.jpg"
  bio              : "Ph.D student in Materials Science"
  location         : "University of Michigan, USA"
  links:
    - label: "Made Mistakes"
      icon: "fa fa-home"
      url: "https://mademistakes.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mmistakes"
  employer         : 
  pubmed           : #"https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  googlescholar    : "https://scholar.google.com/citations?hl=en&user=k-nqUdgAAAAJ&view_op=list_works&sortby=pubdate"
  email            : "aditya.1094@gmail.com?cc=adisun@umich.edu"
  # researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        : 
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "adisun94"
  google_plus      :
  keybase          :
  #instagram        :
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "aditya-sundar-b7a966120/"
  orcid            : #"http://orcid.org/yourorcidurl"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  #twitter          : #"replacethistwitterhandle"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Footer info
#about: >
#    Prof. Spencer H. Bryngelson<br/>
#    College of Computing, <a href="https://cse.gatech.edu/" target="_blank">CSE</a><br/>
#    Georgia Institute of Technology

#coordinates: >
#  <a href="https://codatechsquare.com/" target="_blank">CODA</a><br/>
#  756 W Peachtree St<br/>
#  Atlanta, GA 30332

#information: >
#    <a href="mailto:spencer@caltech.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Spencer via email</a> <br/>
#    <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Use my site as a template!</a> <br/>
#    <a href="/vacancies.html"><i class="fa fa-users fa-1x"></i> Explore openings</a>


# Pages shown in navbar
nav_pages:
  - name: bio
  - name: experience 
# - name: team
  - name: publications
  - name: research
# - name: software
  - name: projects
# - name: about
  - name: teaching

include:
  - .htaccess
  - _pages
  - files

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Sundar
  first_name: [Aditya]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile

